#pull_request_rules:
#  - name: Automatically merge translations
#    conditions:
#      - "author = weblate"
#      - "-conflict"
#      - "current-day-of-week = Sat"
#      - "created-at < 1 day ago"
#    actions:
#      merge:
#        method: squash